/*
* principal amount 50000
* interest rate 13
* Loan Period 3
* Total Payable Amount = 63528.3
 * Monthly payment
      pay only interest every month
      pay every month same interest
      Monthly payable amount = 63528.3/(3*12)
      due = 63528.3 - monthly payable amount
      due = due - monthly payable amount
      if due date exceed add panelty amount, increasing panelty rate every day
 * quaterly (3month payment)
    
 * 6 month payment
 * yearly payment
 */
package loancalculator;


import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;
/**
 *
 * @author sanjok
 */
public class LoanForm extends javax.swing.JInternalFrame {
    
    DefaultTableModel dtm;
    Double payableAmount = 0.0;
    Double totalPayable =0.0;
    Double monthly,quarterly,semiAnually;
    //monthly calculation
    double ir,payment,p,r=0.0;
    //a is loan amount
    double a=0.0,totalPayment=0.0,totalInterestPaid =0.0;
    int n =1 ;
    DecimalFormat df = new DecimalFormat("##.00");
    
    //NumberFormat currencyFormat = NumberFormat.getCurrencyInstance();
    NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("en", "in"));


    NumberFormat interestFormat = NumberFormat.getPercentInstance();

    /**
     * Creates new form NewJFrame
     */
    public LoanForm() {
        initComponents();
       
        dtm = (DefaultTableModel) jTableLoan.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPane = new javax.swing.JPanel();
        jbt_compute = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_annualPayment = new javax.swing.JTextField();
        jtf_totalPayment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jtfTotalInterestPayable = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtf_monthlyPayment = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jtf_quaterlyPayable = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf_semiAnually = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLoan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_principalAmt = new javax.swing.JTextField();
        jtf_rate = new javax.swing.JTextField();
        jtf_period = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jcbMethod = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jbtPrint = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout tblPaneLayout = new javax.swing.GroupLayout(tblPane);
        tblPane.setLayout(tblPaneLayout);
        tblPaneLayout.setHorizontalGroup(
            tblPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        tblPaneLayout.setVerticalGroup(
            tblPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jbt_compute.setText("Compute Loan");
        jbt_compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_computeActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Annually");

        jLabel5.setText("Total Payable");

        jtf_annualPayment.setEditable(false);

        jtf_totalPayment.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Details");

        jLabel8.setText("Total Inerest payable");

        jtfTotalInterestPayable.setEditable(false);

        jLabel10.setText("Monthly Payment");

        jtf_monthlyPayment.setEditable(false);

        jLabel11.setText("Quarterly");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Payments Types:");

        jtf_quaterlyPayable.setEditable(false);
        jtf_quaterlyPayable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_quaterlyPayableActionPerformed(evt);
            }
        });

        jLabel13.setText("Semi-Annually");

        jtf_semiAnually.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_totalPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jtfTotalInterestPayable)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_monthlyPayment)
                                    .addComponent(jtf_quaterlyPayable)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel13))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_semiAnually)
                                    .addComponent(jtf_annualPayment))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTotalInterestPayable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_totalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_monthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_quaterlyPayable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtf_semiAnually, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_annualPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("LoanCalculator");

        jTableLoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.of Payments", "Principal", "Interest", "Total Payable", "Payment", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLoan);
        if (jTableLoan.getColumnModel().getColumnCount() > 0) {
            jTableLoan.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jLabel1.setText("Loan Amount");

        jLabel2.setText("Annual Interest Rate");

        jLabel3.setText("Loan Period");

        jtf_principalAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_principalAmtActionPerformed(evt);
            }
        });

        jcbMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Weekly", "Biweekly", "Monthly", "Bimonthly", "Quarterly", "Semi-Annually", "Annually" }));

        jLabel9.setText("Payment Frequency");

        jLabel14.setText("%");

        jLabel15.setText("Year");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_principalAmt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbMethod, 0, 190, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_rate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jtf_period, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtf_principalAmt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtPrint.setText("Print");
        jbtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbt_compute)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(tblPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtPrint)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_compute)
                    .addComponent(jbtPrint))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

               

    private void jtf_principalAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_principalAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_principalAmtActionPerformed
    
    private void jbt_computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_computeActionPerformed
        // TODO add your handling code here:
            
            Functions loan = new Functions();
            
            p = Double.parseDouble(jtf_principalAmt.getText());
            r = Double.parseDouble(jtf_rate.getText());
            int t = Integer.parseInt(jtf_period.getText());
            String method = (String)jcbMethod.getSelectedItem();
            System.out.println(method);

            a = p;
            
            double annPayment = loan.getAnnualPayment(p, r, t);              
           
            String s = String.valueOf(annPayment);            
            jtf_annualPayment.setText(s);     
            
            dtm.setRowCount(0);

          switch(method){
              case "Daily":
                  n = t*365;
                  ir =r/36500;
                  payment = loan.getPaymentAmount(p,n,ir);
                  totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;                   
                  break;
              
                case "Weekly":
                n = t*52;
                ir =r/5200;
                payment = loan.getPaymentAmount(p,n,ir);
                totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;
                break;
                    
              case "Biweekly":
                n = t*26;
                ir =r/2600;
                payment = loan.getPaymentAmount(p,n,ir);
                totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;
                break;
                  
               case "Semi-Monthly":
                n = t*24;
                ir =r/2400;
                payment = loan.getPaymentAmount(p,n,ir);
                
                break;
                  
               case "Monthly":                   
                    //If Monthly,
                    //r = i / 1200 and N = n * 12
                   n = t*12;
                   ir =r/1200;
                   payment = loan.getPaymentAmount(p,n,ir);
                   totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;
                   break;
                   
                case "Bimonthly":                   
                    //If Monthly,
                    //r = i / 1200 and N = n * 12
                   n = t*6;
                   ir =r/600;
                   payment = loan.getPaymentAmount(p,n,ir);
                   totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;
                   break;
                   
               case "Quarterly":
                   //If Quarterly,
                    //r = i / 400 and N = n * 4                   
                   n = t*4;
                   ir = r/400;
                   payment = loan.getPaymentAmount(p,n,ir);  
                   totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;
                   break;
                   
               case "Semi-Annually":
                   //If Half yearly,
                    //r = i / 200 and N = n * 2
                   n = t*2;
                   ir = r/200;
                   payment = loan.getPaymentAmount(p,n,ir);
                   totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;
                   break;
                   
               case "Annually": 
                   //If Yearly,
                    //r = i / 100 and N = n  
                   n = t;
                   ir = r/100;
                   payment = loan.getPaymentAmount(p,n,ir);
                   totalPayment = payment*n;
                   totalInterestPaid = totalPayment - p;
                   break;
           }
//                      System.out.println(n);
//                   System.out.println(ir+"\n"+payment+"\n"+totalPayment+"\n"+totalInterestPaid);
                   
          double si=0.0, due=0.0;
                for(int i=1; i<=n;){  
                   double amt=p;
                   si = loan.getSimpleInterest(p, 1, ir);
                   due = loan.getDueAmount(p, si, payment);
                    if(due<1.00)
                       due = 0.00;
                    //dtm.addRow(new Object[]{i,amt,si,due});
                    totalPayable = amt+si;
                    
                    dtm.insertRow(dtm.getRowCount(), new Object[]{
                        i,
                        currencyFormat.format(amt),
                        currencyFormat.format(si),
                        currencyFormat.format(totalPayable),
                        currencyFormat.format(payment),
                        currencyFormat.format(due)
                    });
                    i++;
                    p = due;                    

                }
            
            String totalInterest = String.valueOf(Double.parseDouble(df.format(totalInterestPaid)));
            jtfTotalInterestPayable.setText(totalInterest);    
            
           
            String total = String.valueOf(Double.parseDouble(df.format(totalPayment)));
            jtf_totalPayment.setText(total);
            
             
            monthly = loan.getPaymentAmount(a, t*12, r/1200);
            String monthlyPayable = String.valueOf(Double.parseDouble(df.format(monthly)));
            jtf_monthlyPayment.setText(monthlyPayable);
            
            quarterly = loan.getPaymentAmount(a, t*4, r/400);
            String quaterlyPayable = String.valueOf(Double.parseDouble(df.format(quarterly)));
            jtf_quaterlyPayable.setText(quaterlyPayable);
            
            semiAnually = loan.getPaymentAmount(a, t*2, r/200);
            String semiAnuallyPayable = String.valueOf(Double.parseDouble(df.format(semiAnually)));
            jtf_semiAnually.setText(semiAnuallyPayable);
            
    }//GEN-LAST:event_jbt_computeActionPerformed

    private void jtf_quaterlyPayableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_quaterlyPayableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_quaterlyPayableActionPerformed

    private void jbtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrintActionPerformed

        // TODO add your handling code here:
        try{
            boolean print = jTableLoan.print();
            if(print){
                JOptionPane.showMessageDialog(null, "printing");
            }else{
                JOptionPane.showMessageDialog(null, "Error while processing");
            }
            
        }catch(Exception ex){
            
        }
        
    }//GEN-LAST:event_jbtPrintActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableLoan;
    private javax.swing.JButton jbtPrint;
    private javax.swing.JButton jbt_compute;
    private javax.swing.JComboBox jcbMethod;
    private javax.swing.JTextField jtfTotalInterestPayable;
    private javax.swing.JTextField jtf_annualPayment;
    private javax.swing.JTextField jtf_monthlyPayment;
    private javax.swing.JTextField jtf_period;
    private javax.swing.JTextField jtf_principalAmt;
    private javax.swing.JTextField jtf_quaterlyPayable;
    private javax.swing.JTextField jtf_rate;
    private javax.swing.JTextField jtf_semiAnually;
    private javax.swing.JTextField jtf_totalPayment;
    private javax.swing.JPanel tblPane;
    // End of variables declaration//GEN-END:variables
}
